### ISSUE TITLE
Support different calculation mode, to balance speed and security

### ISSUE THREAD

**Issue by mgqa34** [WeBankFinTech/FATE#126]
**Is your feature request related to a problem? Please describe.**
In current time, each iteration of LR\Secureboost will use fate-paillier to re-encrypt all needed data, but it will be very slow, FATE should support more mode to balance speed and security

**Describe the solution you'd like**
Three modes:
1. Slow mode: the same with nowadays, each iteration of algorithm use fate-paillier to re-encrypt all data.
2. Fast mode: just encrypt the data in the first iteration, after that, add the difference part to the encrypted data to get the new encrypted data.
3. Balance mode: mixes of 1st and 2nd mode, user can use self-define parameter to decide how many iterations pass they will re-encrypt all data, and use the difference part to update encrypted data in not re-encrypted iterations.

**Comment by zazd** [comment]
hetero-lr support this by #156
