### ISSUE TITLE
detailed supported documents wanted

### ISSUE THREAD

**Issue by Sinever** [WeBankFinTech/FATE#137]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Sinever** [comment]
where is the more detailed supported documented about how it works and what features it supports and how to use it.

**Comment by dylan-fan** [comment]
If you want to know the features which FATE support, you can read the RELEASE.md file.
In the example module,  we give some examples and documents which told how to use.
In the federatedml modules，we also add some READEME.md file in some algorithms sub-modules.
If you have any other confusions, please tell us.
thanks

**Comment by Sinever** [comment]
ok, thanks.
