### ISSUE TITLE
Lacking of Basic Dashboard Support

### ISSUE THREAD

**Issue by Tianjian** [WeBankFinTech/FATE#18]
**Is your feature request related to a problem? Please describe.**
It's very hard to observe a training progress, when there is no dashboard or visualization of the whole process

**Describe the solution you'd like**
Tensorboard like or at  least something that is on the  same level with the spark dashboard

**Describe alternatives you've considered**
Nope

**Comment by dylan-fan** [comment]
Thanks for your advice. This is a very important feature. We plan to implement the feature (view task list, tracking task progress, visualization, etc) in the next version.
