### ISSUE TITLE
The Information of Deployment Environment is needed

### ISSUE THREAD

**Issue by Madon2019** [WeBankFinTech/FATE#182]
**Describe the bug**
the version of FATE and Deployment environment should be more clearly，where can I get these information？
![mmexport1558789476977](https://user-images.githubusercontent.com/50725045/58369747-5d7b5680-7f31-11e9-82b8-50c1cb39981b.jpg)

**Comment by tanmc123** [comment]
Thanks for asking. What is the version of your pip is using? For higher than version 18.1, this problem is supposed to disapear. 

However, pip version is also needed for deploy doc. Thanks for your suggestion.
