### ISSUE TITLE
error in install requirement.txt

### ISSUE THREAD

**Issue by Italiomilch** [WeBankFinTech/FATE#183]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Italiomilch** [comment]
when I install -r requirement.txt，it shows the following ERROR.


OS: [CentOS]
Browser [chrome]
![FedAIinstallerror1](https://user-images.githubusercontent.com/51027709/58372061-ce7b3800-7f4a-11e9-8a4a-568c258f89cb.PNG)

**Comment by Italiomilch** [comment]
I am using CentOS and python 2.7, and I got the following error.
"ERROR: Could not find a version that satisfies the requirement ipython==6.5.0"

**Comment by tanmc123** [comment]
FATE are supported by python 3.6 only now which has been shown in our deploy doc here: https://github.com/WeBankFinTech/FATE/blob/master/cluster-deploy/README.md#32-software-version-requirements.

Hope that is helpful for you.
