### ISSUE TITLE
The details of HomoLogisticRegression are different from `this paper`

### ISSUE THREAD

**Issue by CodePothunter** [WeBankFinTech/FATE#184]
**Describe the bug**
In this [paragraph](https://github.com/WeBankFinTech/FATE/tree/master/federatedml/logistic_regression#1-homogeneous-lr), it is described "More details is available in this paper". However, the implementation of HomoLR doesn't involve SecureAggregation, which is the major contribution of the paper this paragraph refers to. 

Is there something wrong?

**Comment by tanmc123** [comment]
Yes, there is something wrong in the attached paper. The paper showed before is a paper for Hetero-LR. This one[https://acmccs.github.io/papers/p1175-bonawitzA.pdf](url) is the correct one. However, we haven't realize all the mechanism metioned. The aggregation methods used can be treated as a simple version of the paper described. More secure aggregation methods will be available in the future. 

Thanks for your indication and sorry for your inconvenience.

**Comment by CodePothunter** [comment]
Thanks. If you've fixed it, we can close this issue.
