### ISSUE TITLE
seems 'remote' attribute is missing in the definition of the class RuntimeInstance in the file FATE/arch/api/__init__.py" 

### ISSUE THREAD

**Issue by cacoderquan** [WeBankFinTech/FATE#188]
File ".../PycharmProjects/FATE/arch/api/federation.py", line 73, in remote
    return RuntimeInstance.FEDERATION.remote(obj=obj, name=name, tag=tag, role=role, idx=idx)
AttributeError: 'NoneType' object has no attribute 'remote'

**Comment by maxwong** [comment]
Could you provide your initialization steps?

**Comment by cacoderquan** [comment]
I ran the sh ./examples/hetero_logistic_regression/run_logistic_regression_standalone.sh 
and got the error @maxwong 

Plus, we cannot see the log 
/Users/xiangni/PycharmProjects/FATE/examples/hetero_logistic_regression/../../logs/hetero_logistic_regression_example_standalone_20190531112937/workflow.log: No such file or directory

could you tell me where can we find the log?

**Comment by maxwong** [comment]
Hi @zazd could you provide some information on this issue?

**Comment by zazd** [comment]
@cacoderquan is something wrong in nohup under the path:  ./examples/hetero_logistic_regression/
