### ISSUE TITLE
 'breast_homo_guest.csv' should NOT have a column 'y' ?

### ISSUE THREAD

**Issue by cacoderquan** [WeBankFinTech/FATE#189]
@tanmc123 I saw in the 'breast_homo_guest.csv' has a column y. But for my understanding in the vertical federated learning algorithm the guest should not have labels, right?

**Comment by tanmc123** [comment]
breast_homo_guest.csv is a data for homogenous or called horizontal federated learning. For vertical learning, it is heterogenous LR

**Comment by cacoderquan** [comment]
got it. thanks!
