### ISSUE TITLE
Undefined class KVServiceGrpc in LMDBServicer.java

### ISSUE THREAD

**Issue by colinxiong** [WeBankFinTech/FATE#190]
The class "com.webank.ai.fate.api.eggroll.storage.KVServiceGrpc" is not found in LMDBServicer.java and the package in model "fate-storage-service"

I try to find this class in all project and other branches, but it does not work.

![image](https://user-images.githubusercontent.com/23331015/58534932-23ef6780-821f-11e9-893e-d50988d31c4a.png)

**Comment by colinxiong** [comment]
I find it in kv.proto finally.
As i just compile the part of projects, i lose this class.

**Comment by maxwong** [comment]
This is a class generated by the protobuf / grpc compiler.
You can run `mvn compile` in arch root, and these classes will be generated.

I suppose you are using Intellij IDEA. If so, you can run 'compile' in 'lifecycle' under 'fate-all'. This way can you also generate compiled proto files.

**Comment by colinxiong** [comment]
Thanks a lot.
