### ISSUE TITLE
debconf: delaying package configuration, since apt-utils is not installed

### ISSUE THREAD

**Issue by wwwwww1020** [WeBankFinTech/FATE#202]
**Describe the bug**
When I input 'sh build_standalone_docker.sh', few seconds later it will print that 'debconf: delaying package configuration, since apt-utils is not installed' .However I have installed apt-utils. Furthermore when I finish the install , I tried to run the example. There is an exception 'OSError: loading json file config from '/fate/arch/conf/server_conf.json' failed' . I check the file and find that  the conf doesn't exist. May I ask how to fix it. Thank you 
                                                                   

**Desktop (please complete the following information):**
 - OS: [Ubuntu]
 - Browser [chrome,]

**Comment by paulbaogang** [comment]
Thank you very much for your feedback. This is an omission. We have submitted a PR to fix it. If it is more urgent, we can do this:

1.Delete the generated docker container and image.
2.pull the code.
3.Modify the build_standalone_docker.sh code and change "git archive -o ./docker/standalone/fate.tar $(git rev-parse HEAD) arch/api federatedml workflow examples" to "git archive -o ./docker/standalone /fate.tar $(git rev-parse HEAD) arch federatedml workflow examples".
4.Rebuild a docker.
Try again, thank you

**Comment by wwwwww1020** [comment]
I try again and follow above steps, there is a new exception OSError: loading json file config from '/fate/host_runtime_conf' failed! what should I do now 
Thank you.
