### ISSUE TITLE
if not passed at ./federatedml/test/run_test.sh :34

### ISSUE THREAD

**Issue by kevinew** [WeBankFinTech/FATE#211]
**Describe the bug**
In the file  ./federatedml/test/run_test.sh  
the 34 line should be like this: 
` 34         elif [ $file != _test.py$ ] && [ $1 != /test$ ] ; then
`
not as : 
    elif [[ $file =~ _test.py$ ]] && [[ $1 =~ /test$ ]]; then

**To Reproduce**
1.   sh ./federatedml/test/run_test.sh

**Comment by mgqa34** [comment]
Can the tell me infomation like OS enviroment and other error message?  Here =~ operator is use to  regexp matching.

**Comment by kevinew** [comment]
Just use the ubuntu 16.04

**Comment by kevinew** [comment]
changed to use ubuntu 18.04
