### ISSUE TITLE
Question about the toy example workflow

### ISSUE THREAD

**Issue by YangjieZhou** [WeBankFinTech/FATE#212]
Hi,

    I am running the toy example. And I am confused about the difference between the term "host" and "guest". 

    And "host" and "guest" both exist in the <run_toy_example_cluster.sh> and <run_toy_example_standalone.sh>, do they have the same meaning?

Thank you very much!!

**Comment by mgqa34** [comment]
Hello, In many task, we use "guest" as mainly task handler and "host" as coordinator.  In addition, in algorithm tasks, "guest" means who has label "Y".  Maybe you can referer to following link for more details
https://github.com/WeBankFinTech/FATE/tree/master/federatedml/logistic_regression

**Comment by YangjieZhou** [comment]
@mgqa34
Hi,

I have read the doc in the mentioned Logistic Regression, and have some more confusions.

The document says that there are another server act as "Arbiter" while in the cluster deployment, the workflow didn't associated with this role.

Is that any of the 8 module mentioned in the cluster deployment serve as this role?

Thank you very much!

**Comment by tanmc123** [comment]
@YangjieZhou 

The concept "Arbiter" is not any of those 8 modules. This is a concept has same level with "Guest" and "Host". Think about a federated learning scene, suppose there are three companies, let's name them A company, B company and C company for instance, are going to train a federal model. 

Let say, A is a data comsumer that need to hold a model. B is a data provider that provide some data for trainning this model. To make this federated learning possible to happen, there has to be another institution to aggregate their model during trainning. The third party institution is what we called "Arbiter".

For all these three company, they need to deploy the entire FATE which contains all of your mentioned "8 modules". 

Hope that works for you.

**Comment by YangjieZhou** [comment]
@tanmc123 
Thank you for the answer, in that case, if I want to run a LR example, I should deploy at least 3 Host Frame respectively for "host, guest and arbiter"?

Is there any method that just need 2 Host Frame without a arbiter? Thank you

**Comment by YangjieZhou** [comment]
And one more confusion that does the "exchangeip" associated with the arbiter role? Thanks!

**Comment by tanmc123** [comment]
@YangjieZhou Running LR with only two parties is theoretically possible and hopefully will be added in FATE in the future. However, currently, this mechanizm has not realized yet. A easy way to have similar effect will be put arbiter in a same physical mechine, then you can just deploy two frames and one of them act as both guest and arbiter (or host and arbiter as you like).

As for the "exchangeip", can you offer more details about what you mean?

**Comment by wwwwww1020** [comment]
@tanmc123
Assume there is a guest, the exchangeip should be the arbiter's Serving-server ip. Like the guest link to the arbiter.Is that right?Thank you

**Comment by tanmc123** [comment]
@wwwwww1020 
No, if you have just three parties communicating internally, then no exchangeip is needed. However, if you want to connect with each other through public network, the exchange ip is the proxy that transmitting data .
