### ISSUE TITLE
About the auto-deploy.sh -- grpc instalment

### ISSUE THREAD

**Issue by YangjieZhou** [WeBankFinTech/FATE#219]
**Is your feature request related to a problem? Please describe.**

When the auto-deploy.sh comes to compile the grpc, it can attend the "third_party/protobuf", but there are no files inside and the following commands will get error;

'''
cd third_party/protobuf
./autogen.sh
./configure --prefix=$dir/third_party
'''

the printout of these three lines command is shown below;

[INSTALL] Installing grpc protoc plugins
[INSTALL] Installing root certificates
third_party/protobufdata/projects/fate/storage-service-cxx/third_party/grpc# cd  
d_party/protobuf# **./autogen.sh**cts/fate/storage-service-cxx/third_party/grpc/third
bash: ./autogen.sh: No such file or directory
d_party/protobuf# ./configure --prefix=/data/projects/fate/third_party/grpc/third
bash: ./configure: No such file or directory
d_party/protobuf# maketa/projects/fate/storage-service-cxx/third_party/grpc/third
make: *** No targets specified and no makefile found.  Stop.
d_party/protobuf# make checkjects/fate/storage-service-cxx/third_party/grpc/third
make: *** No rule to make target 'check'.  Stop.
d_party/protobuf# make installcts/fate/storage-service-cxx/third_party/grpc/third
make: *** No rule to make target 'install'.  Stop.
d_party/protobuf# cd /data/projects/fate/storage-service-cxx/ird_party/grpc/third
cts/fate/third_party/* ./third_party/e/storage-service-cxx# rsync -a /data/proje 
(base) root@lxy-PA:/data/projects/fate/storage-service-cxx# 

**Describe the solution you'd like**

Are there some matter with the auto-deploy.sh file? Thanks

**Comment by paulbaogang** [comment]
Did you execute "git submodule update --init --recursive"?Chek if the folder "third_party/protobuf" is empty first.

**Comment by YangjieZhou** [comment]
Hi, the instruction said that this command can be replaced by download 

"the list of glog-0.4.0、grpc-1.19.1、boost-1.68.0、lmdb-0.9.22、protobuf-3.6.1 yourself if conditions permit."

By downloading this git respositories, the protobuf directory also have many files.

**Comment by YangjieZhou** [comment]
@paulbaogang
Hi, the instruction said that this command can be replaced by download

"the list of glog-0.4.0、grpc-1.19.1、boost-1.68.0、lmdb-0.9.22、protobuf-3.6.1 yourself if conditions permit."

By downloading this git respositories, the protobuf directory also have many files.

**Comment by paulbaogang** [comment]
Hello,I hava know your problem,when you download these modules,they also have many sub-modules.So the solution is execute "git submodule update --init --recursive" angin.You can try it.

**Comment by YangjieZhou** [comment]
Ok, I get it. Thank you very much!!

@paulbaogang
And I have observed that the "auto-deploy.sh" will deploy both the <PartyA> and <PartyB>. In that case, is that correct that I can just run the "auto-deploy.sh" just unilaterally?

What's the exact difference between the unilateral deployment and bilateral deployment?

**Comment by YangjieZhou** [comment]
Hi @paulbaogang

When I am running to install the git submodule in "grpc" the submodule
'third_party/libFuzzer'
is failed due to the timeout. And I find that it is due to the "Proxy" as shown below

"fatal: unable to access 'https://chromium.googlesource.com/chromium/llvm-project/llvm/lib/Fuzzer/': Failed to connect to chromium.googlesource.com port 443: Connection timed out"

I am not sure if I can download the 'https://chromium.googlesource.com/chromium/llvm-project/llvm/lib/Fuzzer/' and move it to the "third_party/libFuzzer". Do you guys also meet this problem before?

Thank you very much

**Comment by paulbaogang** [comment]
> Ok, I get it. Thank you very much!!
> 
> @paulbaogang
> And I have observed that the "auto-deploy.sh" will deploy both the and . In that case, is that correct that I can just run the "auto-deploy.sh" just unilaterally?
> 
> What's the exact difference between the unilateral deployment and bilateral deployment?

Hello@YangjieZhou
Thank you for your question.
You can think of both sides of FATE as servers and clients. When you need to cooperate with servers, you can use one-sided deployment on both sides respectively. When you can deploy both servers and clients at the same time, you can use bilateral deployment.

**Comment by paulbaogang** [comment]
> Hi @paulbaogang
> 
> When I am running to install the git submodule in "grpc" the submodule
> 'third_party/libFuzzer'
> is failed due to the timeout. And I find that it is due to the "Proxy" as shown below
> 
> "fatal: unable to access 'https://chromium.googlesource.com/chromium/llvm-project/llvm/lib/Fuzzer/': Failed to connect to chromium.googlesource.com port 443: Connection timed out"
> 
> I am not sure if I can download the 'https://chromium.googlesource.com/chromium/llvm-project/llvm/lib/Fuzzer/' and move it to the "third_party/libFuzzer". Do you guys also meet this problem before?
> 
> Thank you very much
I think there may be some problems with your download source. I suggest that you download it and execute "git submodule update -- init -- recursive" directly under the FATE directory.

**Comment by paulbaogang** [comment]
> Hi @paulbaogang
> 
> When I am running to install the git submodule in "grpc" the submodule
> 'third_party/libFuzzer'
> is failed due to the timeout. And I find that it is due to the "Proxy" as shown below
> 
> "fatal: unable to access 'https://chromium.googlesource.com/chromium/llvm-project/llvm/lib/Fuzzer/': Failed to connect to chromium.googlesource.com port 443: Connection timed out"
> 
> I am not sure if I can download the 'https://chromium.googlesource.com/chromium/llvm-project/llvm/lib/Fuzzer/' and move it to the "third_party/libFuzzer". Do you guys also meet this problem before?
> 
> Thank you very much

Hi @YangjieZhou 
This download source may have problems. You can try to download and put it in the corresponding directory by yourself, or I have downloaded packages that can be sent to you.

**Comment by YangjieZhou** [comment]
@paulbaogang

Thank you for the detailed answer. As for the one-sided deployment on both sides respectively. 

* Should the configuration file in /data/projects/FATE/cluster-deploy/scripts/configurations.sh be the same in both sides?
* And If it shouldn't, this file in two sides should be reversed and which "IP address" should be regarded as the PartyA?
* should each sides both run the "auto-deploy.sh" for the unilateral deployment?

It is really kind of you thanks.

**Comment by paulbaogang** [comment]
> @paulbaogang
> 
> Thank you for the detailed answer. As for the one-sided deployment on both sides respectively.
> 
> * Should the configuration file in /data/projects/FATE/cluster-deploy/scripts/configurations.sh be the same in both sides?
> * And If it shouldn't, this file in two sides should be reversed and which "IP address" should be regarded as the PartyA?
> * should each sides both run the "auto-deploy.sh" for the unilateral deployment?
> 0
> It is really kind of you thanks.

Hello @YangjieZhou 
If you deploy only one side, the configuration file  in /data/projects/FATE/cluster-deploy/scripts/configurations.sh should have only one configuration, not two, just like Federation 0, without Federation 1. Similarly, if you need to deploy two parties, there should be Federation 0, Federation 1;if you need to deploy three parties, there should be Federation 0, Federation 1 and Federation 2. Like this.
Thank for you question.

**Comment by pickonecat** [comment]
@YangjieZhou 

您好，我和你一样在研究，微众的在线学习，怎么运行，
测试了下
sh run_logistic_regression_cluster.sh guest $jobid $guestpartyid $hostpartyid $arbiterpartyid 方式
也是失败了的，失败原因也是数据交互的服务没运行起来，我仔细的查看了代码，也没有找到运行服务的程序。
看了下您问的问题，感觉您应该也在测同样的流程，想问问您，您成功了吗？
测试版的没成功的话，后来测试的auto-deploy 成功了吗？

非常期待您的回复！
