### ISSUE TITLE
Question about the cluster Logistics Regression Example

### ISSUE THREAD

**Issue by YangjieZhou** [WeBankFinTech/FATE#222]
Hi,

When running the homo LR, it will execute "from arch.api import eggroll" and inside the eggroll there is a syntax error in line 26.

def init(job_id=None, mode: WorkMode = WorkMode.STANDALONE):

does this definition want to set the mode default value to WorkMode.STANDALONE ?

**Comment by YangjieZhou** [comment]
I am not sure if the ":" is used to defined the data type of the "mode"? 

But even it has this meaning, the python compiler will raise error when the ":" inside the def sentence as "SyntaxError: invalid syntax"

**Comment by dylan-fan** [comment]
we advise your python version is >= 3.6.
And you can search "Type Hints" about python on google. 
"https://sikasjc.github.io/2018/07/14/type-hint-in-python/ " may be helpful for you

**Comment by YangjieZhou** [comment]
@dylan-fan

I get the problem

When I source the venv/bin/activate, I find that when run "python"  command, it will attend the python2.7 environment. I think it is the establishment in certain file causing this problem.

Can I newly create a venv pointing to python3? and pip install the requirement.txt in https://github.com/WeBankFinTech/FATE/blob/master/requirements.txt

Thanks a lot
