### ISSUE TITLE
About the storage-service-cxx service.sh start

### ISSUE THREAD

**Issue by YangjieZhou** [WeBankFinTech/FATE#224]
Hello,

After running successfully the "auto-deploy.sh", we continue to start the service. And when running the "service.sh" in the /data/projects/fate as "bash service.sh all start" the storage-service-cxx is fail because of the 

"service.sh: line 34: ./storage-service: No such file or directory"

how should I change the command or Can I just start the service in the storage-service "/data/projects/fate/storage-service/service.sh" for **running the cluster deploy example**?

Thank you very much!

**Comment by YangjieZhou** [comment]
Hi, I think the auto-deploy.sh have a certain fail to compile the “storage-service.o” and "storage-service.cc" in /data/projects/fate/storage-service-cxx/ to the executable file "storage-service-0.2".

And I didn't find any command in the auto-deploy.sh or auto-packaging.sh to make this file. Which command can generate the "storage-service-0.2" in the /data/projects/fate/storage-service-cxx/?

Thank you very much!

**Comment by maxwong** [comment]
What are the error messages when you cd into storage-service-cxx and make?

**Comment by YangjieZhou** [comment]
@maxwong 

When I deploy 2 parties.

The latter party always can't directly compile the "grpc" casuing a lask of the executable file "/data/projects/fate/storage-service-cxx/third_party/bin/grpc_cpp_plugin".

As a result, in the "/data/projects/fate/storage-service-cxx" when execute "make" to compile to get the "storage-service-0.2" it will always raise up the error

##########
 DEPENDENCY ERROR

You don't have the grpc c++ protobuf plugin installed in your path.
Please install grpc. You can find it here:

   https://github.com/grpc/grpc

Here is what I get when trying to detect if you have the plugin:

which /data/projects/fate/storage-service-cxx/third_party/bin/grpc_cpp_plugin
Makefile:107: recipe for target 'system-check' failed
make: [system-check] Error 1 (ignored)
############

While the machine of partyA is deployed and compiled successfully with the "/data/projects/fate/storage-service-cxx/third_party/bin/grpc_cpp_plugin"


Could you please tell me what can lead to the same deploy code have different compile result?

**Comment by YangjieZhou** [comment]
Could the difference between the version of Ubuntu in 2 machine cause this situation?

**Comment by YangjieZhou** [comment]
@maxwong What if I couldn't successful install the storage-service-cxx, can It be replaced by the jave version "service.sh" inside the "storage-service"? 

should both party use the "storage-service"? Or can one of them start the storage-service-cxx"?

Really Thanks!!!!!!!!

**Comment by YangjieZhou** [comment]
@maxwong Hi

If I can just cp the successfully installed "/data/projects/fate/storage-service-cxx" into the other party?

I think all it need is the executable files which can be used independently.

**Comment by maxwong** [comment]
`grpc_cpp_plugin` is necessary in Makefile to generate grpc classes. If 2 parties are using the same version of operating system (which has same versions of glibc and so on), it is possible that you can copy one into another.
`grpc_cpp_plugin` can be installed or be found when you have successfully made grpc (which is a third_party dependency of storage-service-cxx). You may want to use `find` command to locate it.

As for `storage-service` and `storage-service-cxx`, the former implementation is based on Java (using JNI). In concurrency situation it may crash. So we recommend users using the c++ implementation whenever possible.
