### ISSUE TITLE
what's the difference between online and offline module

### ISSUE THREAD

**Issue by YangjieZhou** [WeBankFinTech/FATE#225]
Hello,

In the cluster-deploy directory README.md. Under the 4.3. Modify Configuration File there is a note says that 

*Note: tmipList and serving0, serving1 need to be configured only when online deployment is required, and configuration is not required only for offline deployment.*

Is the "online" means for the  cluster providing the online service?

**Comment by dylan-fan** [comment]
online represent online inference serving
