### ISSUE TITLE
The post request in the "workflow/status_tracer_decorator.py"

### ISSUE THREAD

**Issue by YangjieZhou** [WeBankFinTech/FATE#226]
Hello,

When running the "run_toy_example_cluster.sh" which will invoke the "workflow/toy_example_workflow/secure_add_host_workflow.py ", the run() function inside the latter file is decorated by the status_tracer_decorator.status_trace which will invoke the call_back() function.

And this call_back() function will send a post request to a url "http://192.168.0.100:9380/job/jobStatus/test0/host/0" where "test0" is a jobid and the last "0" is the Partyid.

I am confused that which file is act to start this server service? As for the task-manager service, it is not associated with the jobid.

**Comment by yaoyidian** [comment]
the code is quite confusing...... I also encounter this problem!

**Comment by mgqa34** [comment]
The url is used to post-back job status to task-manager and the task-manager use jobid to identify the unique job. What's more,  we use task-manager to start and control the jobs in real scenario, so jobs need to callback job status to task-manager to life cycle management of the job, status_tracer_decorator is also for this.
run_toy_example_cluster.sh or other run_$algorithm_cluster.sh scripts are just help us to be quickly familiar with Fate and for self-debugging too. If you want to know how to start task by task-manager,  have a look at this link: https://github.com/WeBankFinTech/FATE/tree/master/examples/task_manager_examples
