### ISSUE TITLE
Stoping when the eggroll.table is used

### ISSUE THREAD

**Issue by YangjieZhou** [WeBankFinTech/FATE#229]
Hi, 

When I am running the "run_logistics_homo_cluster.sh" as a host role.

The program stuck at the eggroll.init() when the RuntimeInstance.EGGROLL.table("__federation__", job_id, partition=10) which is exectly when the eggroll.table() is runing the self._create_table() which invoke the grpc client funcition self.kv_stub.createIfAbsent(create_table_info)

I check the "self.kv_stub" object creation that the self.channel has the correct port and host.

It seems like the request is sent and keep waiting for the response. And I didn't find the file which set up the KVServiceServicer.

Could you please tell me that what can lead to this problem and is the grpc server start up by some other files?

And if you can provide the module Readme file link for the module including the eggroll, federation and so on. It will really helpful.

Thank you very much!!

**Comment by YangjieZhou** [comment]
I have check the instalment of grpc by running the helloworld.proto to create a simple server and client.

**Comment by yaoyidian** [comment]
i have the same problem, need help!!!!

**Comment by drkingman** [comment]
It seems like the server file cannot be found.

**Comment by maxwong** [comment]
Could you share your server_conf.json?
Normally you can find it under arch/conf/server_conf.json.

**Comment by YangjieZhou** [comment]
The server_conf.json is something like that

{
    "party_id": "1",
    "servers": {
        "manager": {
            "host": "192.168.0.121",
            "grpc.port": 9360,
            "http.port": 9380
        },
        "servings": [
            "192.168.0.100:8001",
            ":8001"
        ],
        "proxy": {
            "host": "192.168.0.121",
            "port": 9370
        },
        "roll": {
            "host": "192.168.0.121",
            "port": 8011
        },
        "federation": {
            "host": "192.168.0.121",
            "port": 9394
        }
    }
}

And I find this conf json in the other server have all the same ip values, while in this server, there is a different value in the "servings". Does it affect?

Thank you!

**Comment by YangjieZhou** [comment]
The server_conf.json is something like that

{
"party_id": "1",
"servers": {
"manager": {
"host": "192.172.0.199",
"grpc.port": 9360,
"http.port": 9380
},
"servings": [
"192.172.0.182:8001",
":8001"
],
"proxy": {
"host": "192.172.0.199",
"port": 9370
},
"roll": {
"host": "192.172.0.199",
"port": 8011
},
"federation": {
"host": "192.172.0.199",
"port": 9394
}
}
}

And I find this conf json in the other server have all the same ip values, while in this server, there is a different value in the "servings". Does it affect?

Thank you!

**Comment by maxwong** [comment]
This looks like a configuration issue so we have to check on logs to see what goes wrong.

Please check `fate-roll.log` at 192.172.0.199. You can `tail -f` it in one terminal, and run `eggroll.init(job_id, 1)` in another terminal to see if there is any error message in `fate-roll.log`, or what are the last messages before getting stuck. Thank.

Oh, almost forgot. Serving module does not affect eggroll.
