### ISSUE TITLE
arch/api/utils/donwload.py fails to deserialize custom objects using pickle

### ISSUE THREAD

**Issue by zengjice** [WeBankFinTech/FATE#230]
**Describe the bug**
1. failed to download a dtable which had custom object by using arch/api/utils/donwload.py
2. copy download.py to another directory can work
3. the download script in arch/api/utils will use the pickle.py in the same directory instead of the native pickle

**Comment by dylan-fan** [comment]
arch/api/utils/pickle.py is not used, which is said by eden . It can be deleted in next version
