### ISSUE TITLE
errors occures when  we use FATE

### ISSUE THREAD

**Issue by lytofd** [WeBankFinTech/FATE#257]
we  installs crn on a  ubuntu server,to fasten  trainning speed on FATE,but error occures in grpc 
      Failed to set TCP_NODELAY
https://github.com/grpc/grpc/blob/3891e03ece195810a521ec379a512bdc2e4262cd/src/core/lib/iomgr/socket_utils_common_posix.cc#L214
this link is the source code of grpc  ,we trace this error on line 221, to prove our idea, l write a simple client-server model, after create a socket, l insert a piece of code which is :
      int low_lengcy = 1;
      int val = (low_lengcy!=0);
      int newval;
      socklen_t intlen = sizeof(newval);
      if (0 != setsockopt(sockfd, IPPROTO_TCP, TCP_NODELAY, &val, sizeof(val)))
    {
      printf("设置失败");
      exit(1);
    }
     if (0 != getsockopt(sockfd, IPPROTO_TCP, TCP_NODELAY, &newval, &intlen))
    {
      printf("获取属性失败");
      exit(1);
    }
    if ((newval != 0) != val)
    {
     printf("tcp设置失败");
    }
  when we installs crn, error occures, after remove crn, error disappears.

**Comment by zengjice** [comment]
This seems to be the error caused by crn? 
FATE has not tried to use crn for accelerated training.
Thanks.
