### ISSUE TITLE
There is a WeChat group in order to discuss about FATE

### ISSUE THREAD

**Issue by wwwwww1020** [WeBankFinTech/FATE#259]
There is a WeChat group for people talk about FATE. This group can help us to communicate, discuss and share the experience with each other about FATE. Welcome aboard!
![fategroup](https://user-images.githubusercontent.com/39673228/60228093-1da6e680-98c4-11e9-900b-404d63bb362f.jpg)

**Comment by wangxuhubu** [comment]
The code has expired, Could you please resend it

**Comment by caimantian007** [comment]
The code has expired, Could you please resend it

**Comment by pangzx1** [comment]
Hello, your QR code has expired. Can you re-enter the new QR code?

**Comment by Hyberlion** [comment]
The code has expired, Could you please resend it
