### ISSUE TITLE
FATE支持 众向联邦学习吗   label和feature分离在不同的数据方

### ISSUE THREAD

**Issue by kevinew** [WeBankFinTech/FATE#268]

**Comment by tanmc123** [comment]
Your question is about whether we support vertical federated learning and the answer is Yes.

In FATE, we call it heterogeneous federated learning. Up to now, we support hetero-lr, hetero-secureboosting and several hetero-feature engineering methods. Feel free to try them in our examples. And if you have any future question, please contact us without hesitation.

**Comment by kevinew** [comment]
Data-A  only has label,  Data-B only has feature  and doesn't have label，  can it be trained?

**Comment by tanmc123** [comment]
@kevinew Yes, that's what exactly hetero-federated ml do. This is  an example showing how it works: https://github.com/WeBankFinTech/FATE/tree/master/federatedml/logistic_regression#2-heterogeneous-lr.

**Comment by kevinew** [comment]
Thanks tanmc123, I'll try this case and hope to take effect after been deployed.
