### ISSUE TITLE
about cluster storage-service

### ISSUE THREAD

**Issue by YangjieZhou** [WeBankFinTech/FATE#269]
Hi,

I am confused that what does the partition work for in the "_DTable" or "eggroll.table()" function.

I find the data will be saved in the local machine by LMDB format. What if the data used is a enormous dataset saved in the HDFS, will the LMDB linked with the _DTable also be too large on the machine?

Thank you very much!

**Comment by dylan-fan** [comment]
_DTable is a distributed data structure. The data in _DTable  is not only in one machine.
