### ISSUE TITLE
Data question of Hetero_lr 

### ISSUE THREAD

**Issue by three3stones** [WeBankFinTech/FATE#270]
Hello!
In hetero_lr, the data of breast_a and breast_b both have x0~x9 labels, are these labels consistent?

**Comment by zazd** [comment]
Actually, x* in breast_a and breast_b including x0~x9 are the features of data, the label of this data is in breast_b with title "y"

**Comment by three3stones** [comment]
thanks,  but I have another question.
In the prediction of hetero_lr, guest has x0~x9 features, host has x0~x19 features.
So, if we have a sample with x0~x19 features, but guest don't have all features, how should we predict?

**Comment by zazd** [comment]
If the size of train_data's features is different from predict data's, it will cause a error. So you should make they same, for example, set the missing feature to 0, but actually it is not recommended to do so.
