### ISSUE TITLE
About the auc and precision

### ISSUE THREAD

**Issue by mlchuxueing** [WeBankFinTech/FATE#271]
Hello,
when i run the cluster versin of hetero logistic regression,after  finish the train process,
i only find the auc and precision value in guest ,and host eval_result is None.
I would like to ask ,the result in guest is the result after vertical federated? 
Or, how i can get the result (auc and precision) of vertical federatd?
Thank you very much!

**Comment by dylan-fan** [comment]
“the result in guest is the result after vertical federated？”  The answer is Yes.
Because of label such as "Y"  is only existed in the guest role.
