### ISSUE TITLE
About the new dependency "redis"

### ISSUE THREAD

**Issue by YangjieZhou** [WeBankFinTech/FATE#272]
Hi,

Could you please give a bried introduction about what does the redis works for?

Does it word as a monitor for task queue? If it does, what kind of task is in the queue?

Thank you very much!!

**Comment by dylan-fan** [comment]
Now redis in only used in fate-serving.

**Comment by zengjice** [comment]
Hi yangjie,

In the current version redis is only used by fate-serving. It is mainly used to cache the inference results of remote parties  to reduce the elapsed of federated inference. However, future redis will be used for other system.
Thanks.
