### ISSUE TITLE
About 'auto - deploy. sh' and 'configurations.sh'

### ISSUE THREAD

**Issue by Yuki-99** [WeBankFinTech/FATE#278]
**Is your feature request related to a problem? Please describe.**
According to the introduction, modifying the configuration items corresponding to the configurations.sh file according to the configuration, before execute the auto-packaging.sh(or auto-deploy.sh) script,like this:
partyA.id | Indicates the partyid of partyA
A.MS-ip | Indicates the node where the meta-Service module of partyA is located.
A.F-ip | Indicates the ip of the node where the federation module of partyA is located.
A.P-ip | Indicates the ip of the node where partyA's Proxy module is located.
A.R-ip | Indicates the ip of the node where the party module's Roll module is located.
A.TM-ip | Indicates the server ipexchange where the partyA's Task-manager is located.
A.S-ip | Indicates the server ip of the partyA's Serving-server. If there are multiple, the number is incremented.
A.E-ip | Indicates the server ip of partyA's Egg. If there are more than one, add the number increment.
exchangeip | Exchange server ip

It must be mentioned that,I only make cluster-deploy on one computer.Here's how I modified it:
#!/bin/bash
user=app
dir=/data/projects/fate
mysqldir=/data/projects/common/mysql/mysql-8.0
javadir=/data/projects/common/jdk/jdk1.8
venvdir=/data/projects/fate/venv
redispass=fate1234
partylist=(10000)
JDBC0=(192.168.**.** A.dbname A.user A.password)
iplist=(192.168.**.** 192.168.**.** 192.168.**.** 192.168.**.** 192.168.**.** 192.168.**.**)
fedlist0=(192.168.**.**)
meta0=(192.168.**.**)
proxy0=(192.168.**.**)
roll0=(192.168.**.**)
egglist0=(192.168.**.**)
tmlist0=(192.168.**.**)
serving0=(192.168.**.**)
exchangeip=exchangeip

**Describe alternatives you've considered**
Execute ”auto-deploy.sh“, after the changes mentioned above, the following statement appears:

app$: sh auto-deploy.sh
copy is ok!
The authenticity of host '192.168.**.**(192.168.**.**)' can't be established.
ECDSA key fingerprint is SHA256:*****
ECDSA key fingerprint is MD5:******
Are you sure youwant to continue connecting (yes/no)? yes
Warning:Permanently added '192.168.**.**'(ECDSA) to the list of known hosts.
Authentication failed.
lost conntecting
app@192.168.**.**'s password:******
cd /data/projects/fate
tar -zxf fate.tar
rm -rf fate.tar
exit
Logout
Connection to 192.168.**.** closed.
......
So，Is there any problem with my modification？
Thank you for your time!

**Comment by zzzcq** [comment]
> **Is your feature request related to a problem? Please describe.**
> According to the introduction, modifying the configuration items corresponding to the configurations.sh file according to the configuration, before execute the auto-packaging.sh(or auto-deploy.sh) script,like this:
> partyA.id | Indicates the partyid of partyA
> A.MS-ip | Indicates the node where the meta-Service module of partyA is located.
> A.F-ip | Indicates the ip of the node where the federation module of partyA is located.
> A.P-ip | Indicates the ip of the node where partyA's Proxy module is located.
> A.R-ip | Indicates the ip of the node where the party module's Roll module is located.
> A.TM-ip | Indicates the server ipexchange where the partyA's Task-manager is located.
> A.S-ip | Indicates the server ip of the partyA's Serving-server. If there are multiple, the number is incremented.
> A.E-ip | Indicates the server ip of partyA's Egg. If there are more than one, add the number increment.
> exchangeip | Exchange server ip
> 
> It must be mentioned that,I only make cluster-deploy on one computer.Here's how I modified it:
> #!/bin/bash
> user=app
> dir=/data/projects/fate
> mysqldir=/data/projects/common/mysql/mysql-8.0
> javadir=/data/projects/common/jdk/jdk1.8
> venvdir=/data/projects/fate/venv
> redispass=fate1234
> partylist=(10000)
> JDBC0=(192.168.**.** A.dbname A.user A.password)
> iplist=(192.168.**.** 192.168.**.** 192.168.**.** 192.168.**.** 192.168.**.** 192.168.**.**)
> fedlist0=(192.168.**.**)
> meta0=(192.168.**.**)
> proxy0=(192.168.**.**)
> roll0=(192.168.**.**)
> egglist0=(192.168.**.**)
> tmlist0=(192.168.**.**)
> serving0=(192.168.**.**)
> exchangeip=exchangeip
> 
> **Describe alternatives you've considered**
> Execute ”auto-deploy.sh“, after the changes mentioned above, the following statement appears:
> 
> app$: sh auto-deploy.sh
> copy is ok!
> The authenticity of host '192.168.**.**(192.168.**.**)' can't be established.
> ECDSA key fingerprint is SHA256:*****
> ECDSA key fingerprint is MD5:******
> Are you sure youwant to continue connecting (yes/no)? yes
> Warning:Permanently added '192.168.**.**'(ECDSA) to the list of known hosts.
> Authentication failed.
> lost conntecting
> app@192.168.**.**'s password:******
> cd /data/projects/fate
> tar -zxf fate.tar
> rm -rf fate.tar
> exit
> Logout
> Connection to 192.168.**.** closed.
> ......
> So，Is there any problem with my modification？
> Thank you for your time!

@Yuki-99 
Hello, there is no problem with your modification.The problem is the server of execute the ”auto-deploy.sh“ should has the right to login the deploy server('192.168.**.**') without encryption,even they are the same server.Only in this way the ”auto-deploy.sh“ can be execute fluently.
