### ISSUE TITLE
启动egg服务时无法正常启动grpc服务

### ISSUE THREAD

**Issue by sookieqin** [WeBankFinTech/FATE#279]
**Describe the bug**
参考https://github.com/WeBankFinTech/FATE/tree/master/cluster-deploy 部署文档操作，执行
sh /data/projects/fate/services.sh 时发现grpc服务启动失败。

**Additional context**
修改/data/projects/fate/python/processor.sh脚本，在首行加入`source /data/projects/fate/venv/bin/activate`后，即可正常启动。

**Comment by Yuki-99** [comment]
@sookieqin Hello，how is your file ‘/data/projects/fate/services.sh’ generated smoothly? Thank you!

**Comment by sookieqin** [comment]
> @sookieqin Hello，how is your file ‘/data/projects/fate/services.sh’ generated smoothly? Thank you!
just follow the introduction, but make a few modifications before execute "sh /data/projects/fate/services.sh":
1. replace 'storage-serivice-cxx' in the services.sh file with 'storage-serivice'
2.add 'source /data/projects/fate/venv/bin/activate' in the /data/projects/fate/python/processor.sh file

Hope it works for u.

**Comment by Yuki-99** [comment]
> > @sookieqin您好，您的文件'/data/projects/fate/services.sh'如何顺利生成？谢谢！
> > 只需按照介绍，但在执行“sh /data/projects/fate/services.sh”之前进行一些修改：
> 
> 1. 使用
>    / data / projects / fate / python / processor中的'storage- serivice'2.add'source / data / projects / fate / venv / bin / activate' 替换services.sh文件中的'storage- serivice -cxx' .sh文件
> 
> 希望它对你有用。

Thank you for your last reply. There are still problems.
According to the introduction, modifying the configuration items corresponding to the configurations.sh file according to the configuration, before execute the auto-packaging.sh script.
It must be mentioned that,I only make cluster-deploy on one computer.How to modify the configurations.sh？Thank you for your time.

**Comment by dylan-fan** [comment]
> > @sookieqin Hello，how is your file ‘/data/projects/fate/services.sh’ generated smoothly? Thank you!
> > just follow the introduction, but make a few modifications before execute "sh /data/projects/fate/services.sh":
> 
> 1. replace 'storage-serivice-cxx' in the services.sh file with 'storage-serivice'
>    2.add 'source /data/projects/fate/venv/bin/activate' in the /data/projects/fate/python/processor.sh file
> 
> Hope it works for u.

don't advice to replace "replace 'storage-serivice-cxx' in the services.sh file with 'storage-serivice'"

**Comment by pangzx1** [comment]
Hi:
      I encountered some problems when deploying, I hope to discuss with you! The following is a description of my problem:

When I executed the "sh services.sh all start" command in the "/data/projects/fate" directory, I found the following problem:
[INFO] processing: storage-service-cxx
--------------
Service not running
So when I test the distributed version, I will show that my RPC call failed in the log.

How do you generate the "processor" folder, I can't find this folder in my "python" directory.
How can I successfully generate the "processor" folder?
thank you very much!

**Comment by sookieqin** [comment]
> Hi:
>       I encountered some problems when deploying, I hope to discuss with you! The following is a description of my problem:
> 
> ## When I executed the "sh services.sh all start" command in the "/data/projects/fate" directory, I found the following problem:
> [INFO] processing: storage-service-cxx
> Service not running
> So when I test the distributed version, I will show that my RPC call failed in the log.
> 
> How do you generate the "processor" folder, I can't find this folder in my "python" directory.
> How can I successfully generate the "processor" folder?
> thank you very much!

1. processor.sh is a script in "/data/projects/fate/python" 
2. if storage-service-cxx failed to start, you can check log files under folder "/data/projects/fate/storage-service-cxx/logs"  or you can try this: `cd /data/projects/fate/storage-service-cxx; make clean; make; sh service.sh start`

**Comment by pangzx1** [comment]
> > 嗨：
> >       我在部署时遇到了一些问题，希望能与您讨论！以下是我的问题的描述：
> > ## 当我在“/ data / projects / fate”目录中执行“sh services.sh all start”命令时，我发现了以下问题：
> > [INFO]处理：storage-service-cxx 
> > 服务没有运行
> > 所以当我测试分布式版本时，我会在日志中显示我的RPC调用失败。
> > 如何生成“processor”文件夹，我在“python”目录中找不到该文件夹​​。
> > 如何成功生成“处理器”文件夹？
> > 非常感谢你！
> 
> 1. processor.sh是“/ data / projects / fate / python”中的脚本
> 2. 如果storage-service-cxx无法启动，您可以检查文件夹“/ data / projects / fate / storage-service-cxx / logs”下的日志文件，或者您可以尝试： `cd /data/projects/fate/storage-service-cxx; make clean; make; sh service.sh start`

Hi,
      Thank you very much for your answer. I still have problems. I am looking at the "error.log" file under the "/data / projects / fate / storage-service-cxx / logs" folder. Found the following error:

Service.sh: line 34: ./storage-service: No such file or directory

It shows that there is no "storage-service" file in the current directory.
Do you know what is going on?
How is your "storage-service" file generated smoothly? Or can your "storage-service" file be sent to my mailbox for me to refer to? ? (1554528585@qq.com)
thank you very much!
