### ISSUE TITLE
The egg node

### ISSUE THREAD

**Issue by YangjieZhou** [WeBankFinTech/FATE#281]
Hi,

I am wondering if the "egg node" just need to start the "task manager" service and the "storage-service-cxx"? 

And it also means that I can only run the workflow on the host which I deploy the "federation"?

**Comment by dylan-fan** [comment]
please describe your issue clearly

**Comment by zzzcq** [comment]
> Hi,
> 
> I am wondering if the "egg node" just need to start the "task manager" service and the "storage-service-cxx"?
> 
> And it also means that I can only run the workflow on the host which I deploy the "federation"?

@YangjieZhou 
Actually, the "egg node" need to start the "storage-service-cxx", the other modules is not necessarily, but you can deploy other modules on the same node.And the "task manager" service is deployed on one of the "egg node",not each node.
The service is distributed, you can run the workflow on each host.
Thank you for your question.

Thank you for your question.

**Comment by YangjieZhou** [comment]
@zzzcq 

And I find that when we create a distributed DTable, the egg node will automatically create a LMDB(including the data.mdb and lock.mdb) which is proportional to the read-in csv file. 

It seems like that the data in the csv were copied to the specific local dir. Have I understood it correctly?

Thank you very much!
