### ISSUE TITLE
Tensorflow FL

### ISSUE THREAD

**Issue by crownpku** [WeBankFinTech/FATE#29]
Google pulished [their version of Tensorflow FL stack](https://www.tensorflow.org/federated/federated_learning). They seem to be specifically for horizontal FL with large number of guests, with models wrapped in Keras.

I'm wondering if FATE team is also looking into it, and what your thoughts are? Can we even embed it into the FATE as part of the Horizontal FL with deep learning?

Thanks!

**Comment by dylan-fan** [comment]
Thank you for your attention.
The TensorFlow Federated (TFF) platform is a good platform published by Google. We are reading relevant paper&code, and learned a lot from that. 
IF embed TensorFlow Federated into FATE?  It will take some time to evaluator by FATE Team. 
FATE works on building a scalable production system for Federated Learning. Any good solutions can be taken into consideration.
