### ISSUE TITLE
运行run_toy_example_cluster.sh guest一直卡住

### ISSUE THREAD

**Issue by willysys** [WeBankFinTech/FATE#291]
部署好host和guest两台机器之后，运行run_toy_example_cluster.sh 示例，但是guest端一直卡住了。但是查看各个模块的日志，也没有发现错误。

**Comment by mgqa34** [comment]
Can you please give more information? like roll logs

**Comment by mgqa34** [comment]
Long time no reply, close it, if needed, please reopen the issue
