### ISSUE TITLE
bug when install at 7step

### ISSUE THREAD

**Issue by nickzhou123** [WeBankFinTech/FATE#296]
Step 7/9 : RUN apt-get update && apt-get install libgmp3-dev -y && apt-get install -y libmpfr-dev libmpfr-doc libmpfr4 libmpfr4-dbg && apt-get install libmpc-dev -y
 ---> Running in a908d36d4503
Get:1 http://deb.debian.org/debian buster InRelease [118 kB]
Get:2 http://security.debian.org/debian-security buster/updates InRelease [39.1 kB]
Get:3 http://security.debian.org/debian-security buster/updates/main amd64 Packages [42.5 kB]
Get:4 http://deb.debian.org/debian buster-updates InRelease [46.8 kB]
Get:5 http://deb.debian.org/debian buster/main amd64 Packages [7897 kB]
Fetched 8143 kB in 27s (307 kB/s)
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
The following NEW packages will be installed:
  libgmp3-dev
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 15.7 kB of archives.
After this operation, 22.5 kB of additional disk space will be used.
Get:1 http://deb.debian.org/debian buster/main amd64 libgmp3-dev amd64 2:6.1.2+dfsg-4 [15.7 kB]
debconf: delaying package configuration, since apt-utils is not installed
Fetched 15.7 kB in 2s (9017 B/s)
Selecting previously unselected package libgmp3-dev:amd64.
(Reading database ... 24544 files and directories currently installed.)
Preparing to unpack .../libgmp3-dev_2%3a6.1.2+dfsg-4_amd64.deb ...
Unpacking libgmp3-dev:amd64 (2:6.1.2+dfsg-4) ...
Setting up libgmp3-dev:amd64 (2:6.1.2+dfsg-4) ...
Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package libmpfr4
E: Unable to locate package libmpfr4-dbg
The command '/bin/sh -c apt-get update && apt-get install libgmp3-dev -y && apt-get install -y libmpfr-dev libmpfr-doc libmpfr4 libmpfr4-dbg && apt-get install libmpc-dev -y' returned a non-zero code: 100
+ rm docker/standalone/fate.tar
+ rm docker/standalone/requirements.txt

**Comment by wangxuhubu** [comment]
so do i

**Comment by wangxuhubu** [comment]
Could you tell what your environment ?
I have used Ubuntu 16.04 LTS and Ubuntu 18.04, but i cannot resolve this problem at all

**Comment by nickzhou123** [comment]
jdk1.8
python3.6
virtualenv
mysql8.0
redis-5.0.4
docker client 18.09.8
docker server 18.09.8
CentOS7.2

**Comment by nickzhou123** [comment]
solution：
/docker/standalone/Dockerfile:

FROM python:3.6

WORKDIR /fate

COPY . /fate

RUN rm /bin/sh && ln -sf /bin/bash /bin/sh

RUN tar -xf fate.tar

RUN rm fate.tar
RUN apt-get update && apt-get -y install wget && apt-get -y install libc6 libgmp10 multiarch-support
RUN wget http://ftp.cn.debian.org/debian/pool/main/m/mpfr4/libmpfr4_3.1.2-2_amd64.deb
RUN wget http://ftp.cn.debian.org/debian/pool/main/m/mpfr4/libmpfr4-dbg_3.1.2-2_amd64.deb
RUN dpkg -i libmpfr4_3.1.2-2_amd64.deb
RUN dpkg -i libmpfr4-dbg_3.1.2-2_amd64.deb

RUN apt-get update && apt-get install libgmp3-dev -y && apt-get install -y libmpfr-dev libmpfr-doc libmpfr4 libmpfr4-dbg && apt-get install libmpc-dev -y

RUN pip install -r requirements.txt

ENV PYTHONPATH /fate

**Comment by wangxuhubu** [comment]
thanks a lot, I have changed the dockerfile like yours, and it worked out.

**Comment by zzzcq** [comment]
> Step 7/9 : RUN apt-get update && apt-get install libgmp3-dev -y && apt-get install -y libmpfr-dev libmpfr-doc libmpfr4 libmpfr4-dbg && apt-get install libmpc-dev -y
> ---> Running in a908d36d4503
> Get:1 http://deb.debian.org/debian buster InRelease [118 kB]
> Get:2 http://security.debian.org/debian-security buster/updates InRelease [39.1 kB]
> Get:3 http://security.debian.org/debian-security buster/updates/main amd64 Packages [42.5 kB]
> Get:4 http://deb.debian.org/debian buster-updates InRelease [46.8 kB]
> Get:5 http://deb.debian.org/debian buster/main amd64 Packages [7897 kB]
> Fetched 8143 kB in 27s (307 kB/s)
> Reading package lists...
> Reading package lists...
> Building dependency tree...
> Reading state information...
> The following NEW packages will be installed:
> libgmp3-dev
> 0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
> Need to get 15.7 kB of archives.
> After this operation, 22.5 kB of additional disk space will be used.
> Get:1 http://deb.debian.org/debian buster/main amd64 libgmp3-dev amd64 2:6.1.2+dfsg-4 [15.7 kB]
> debconf: delaying package configuration, since apt-utils is not installed
> Fetched 15.7 kB in 2s (9017 B/s)
> Selecting previously unselected package libgmp3-dev:amd64.
> (Reading database ... 24544 files and directories currently installed.)
> Preparing to unpack .../libgmp3-dev_2%3a6.1.2+dfsg-4_amd64.deb ...
> Unpacking libgmp3-dev:amd64 (2:6.1.2+dfsg-4) ...
> Setting up libgmp3-dev:amd64 (2:6.1.2+dfsg-4) ...
> Reading package lists...
> Building dependency tree...
> Reading state information...
> E: Unable to locate package libmpfr4
> E: Unable to locate package libmpfr4-dbg
> The command '/bin/sh -c apt-get update && apt-get install libgmp3-dev -y && apt-get install -y libmpfr-dev libmpfr-doc libmpfr4 libmpfr4-dbg && apt-get install libmpc-dev -y' returned a non-zero code: 100
> 
> * rm docker/standalone/fate.tar
> * rm docker/standalone/requirements.txt

@nickzhou123 
Thank for your pointing out.
After testing, Ubuntu does not support the automatic installation of libmpfr4 packages, instead of libmpfr6, which may require you to modify docker/standalone/Docker file: RUN apt-get update & apt-get install libgmp3-dev-y & apt-get-install-y libmpfr-dev libmpfr-doc libmpfr4-dbg & apt-get-install-bmpc-d Ev-y
Amendment to
RUN apt-get update & apt-get install libgmp3-dev-y & apt-get install-y libmpfr-dev libmpfr-doc libmpfr6 & apt-get install libmpc-dev-y
It's true that this docker guidance document is a bit old, and we'll update it as soon as possible.
Thank you.
