### ISSUE TITLE
Discussions

### ISSUE THREAD

**Issue by dylan-fan** [WeBankFinTech/FATE#32]
This issue is specially opened for discussion. Here, you can feedback some problem such as install problem when you install FATE or new feature which you think is important for you. 
Finally， hope to use English to ask your questions.
Thanks.
dylanfan

**Comment by dylan-fan** [comment]
When you installed FATE ,  What was the worst experience?

**Comment by zazd** [comment]
For some cooperative partners, docker for cluster is necessary, because they have to ask for more physical computers. This may cost more time and resources for them but just experience FATE they want.

**Comment by ZZIQIN** [comment]
@dylan-fan 
    hi,can you give a sketch to explain the relationship between the various components in the cluster mode? I don't quite understand how to deploy a cluster.

**Comment by cacoderquan** [comment]
After installed the packages, I tried to run  "sh run_logistic_regression_standalone.sh". But it is extremely slow. it keeps printing something like 
cat: /fate/examples/homo_logistic_regression/../../logs/logistic_regression_example_standalone_20190528090656/workflow.log: No such file or directory
please wait or check more info in /fate/examples/homo_logistic_regression/../../logs/logistic_regression_example_standalone_20190528090656/workflow.log

In general, how lone does it takes to run the program? Is there any way to accelerate the process? Thanks.

**Comment by tanmc123** [comment]
@cacoderquan It should be completed in one minute. If not, could you please check logs in this path: /fate/examples/homo_logistic_regression/../../logs/logistic_regression_example_standalone_20190528090656/   and see if there is a status_tracer_decorator.log file exist and see if there is error in it? Or, is there any error info in nohup file in your current path?

**Comment by cacoderquan** [comment]
@tanmc123 Thanks. But could you tell me how to go to /fate/examples/homo_logistic_regression/../../logs/logistic_regression_example_standalone_20190528090656/

I type cd examples/homo_logistic_regression/../../logs/logistic_regression_example_standalone_20190528090656/  but got errors like   

root@f94b7a1fdfe7:/fate# cd examples/homo_logistic_regression/../../logs/logistic_regression_example_standalone_20190528090656/
bash: cd: examples/homo_logistic_regression/../../logs/logistic_regression_example_standalone_20190528090656/: No such file or directory
r

**Comment by tanmc123** [comment]
@cacoderquan well, in your current path, you can just type cd ../../logs/logistic_regression_example_standalone_20190528090656/

**Comment by cacoderquan** [comment]
Thanks. But I type cd ../../logs/hetero_logistic_regression_example_standalone_20190529012020/
it does not work(I use another container)

root@45c7dd1d05a1:/fate# cd ../../logs/hetero_logistic_regression_example_standalone_20190529012020/
bash: cd: ../../logs/hetero_logistic_regression_example_standalone_20190529012020/: No such file or directory

**Comment by cacoderquan** [comment]
find there is a new logs directory, but could not find any results under it.

**Comment by cacoderquan** [comment]
root@45c7dd1d05a1:/fate# ls
Dockerfile  arch  data  examples  federatedml  logs  requirements.txt  workflow
root@45c7dd1d05a1:/fate# cd logs
root@45c7dd1d05a1:/fate/logs# ls
root@45c7dd1d05a1:/fate/logs#

**Comment by cacoderquan** [comment]
@tanmc123

**Comment by tanmc123** [comment]
You should be able to see three nohup files in your example/homo_logistic_regression folder. Please see if there is any error info in one of them.

**Comment by cacoderquan** [comment]
config path is /fate/examples/hetero_logistic_regression/conf/guest_runtime_conf.json_hetero_logistic_regression_example_standalone_20190529012020 
jobid is hetero_logistic_regression_example_standalone_20190529012020 
Traceback (most recent call last): 
  File "/fate/arch/api/utils/file_utils.py", line 40, in load_json_conf 
    with open(json_conf_path) as f: 
FileNotFoundError: [Errno 2] No such file or directory: '/fate/arch/conf/server_conf.json' 


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "../../workflow/hetero_lr_workflow/hetero_guest_workflow.py", line 22, in <module>
    from workflow.workflow import WorkFlow
  File "/fate/workflow/workflow.py", line 52, in <module>
    from workflow import status_tracer_decorator
  File "/fate/workflow/status_tracer_decorator.py", line 30, in <module>
    server_conf = file_utils.load_json_conf("arch/conf/server_conf.json")
  File "/usr/local/lib/python3.6/site-packages/cachetools/__init__.py", line 46, in wrapper
    v = func(*args, **kwargs)
  File "/fate/arch/api/utils/file_utils.py", line 43, in load_json_conf
    raise EnvironmentError("loading json file config from '{}' failed!".format(json_conf_path))
OSError: loading json file config from '/fate/arch/conf/server_conf.json' failed!

**Comment by cacoderquan** [comment]
seems there is some error on loading json file config

**Comment by cacoderquan** [comment]
@tanmc123  this confuses me because I look at server_conf.json which has no problem (as below)

{
	"servers": {
		"roll": {
			"host": "localhost",
			"port": 8011
		},
		"federation": {
			"host": "localhost",
			"port": 9394
		},
		"manager": {
			"host": "localhost",
			"http.port": 9380,
			"grpc.port": 9360
		},
		"servings": [
			"127.0.0.1:8000"
		],
		"proxy": {
			"host": "localhost",
			"port": 9370
		}
	}
}

**Comment by cacoderquan** [comment]
@tanmc123 I tried to debug it, but could not find any solutions. Could you give me some hint/suggestions ? Thanks a lot!

**Comment by tanmc123** [comment]
@cacoderquan Have you add /fate into you PYTHONPATH enviroment? 
Like 

export $PYTHONPATH=/fate

**Comment by cacoderquan** [comment]
I have added /fate into my PYTHONPATH enviroment but still get the same error

root@d28bbf5328ac:/fate/examples/hetero_logistic_regression#  echo $PYTHONPATH
/fate
root@d28bbf5328ac:/fate/examples/hetero_logistic_regression# ls
conf  kill.sh  run_arbiter.sh  run_guest.sh  run_host.sh  run_logistic_regression.sh  run_logistic_regression_cluster.sh  run_logistic_regression_standalone.sh
root@d28bbf5328ac:/fate/examples/hetero_logistic_regression# sh run_logistic_regression_standalone.sh

**Comment by cacoderquan** [comment]
@tanmc123

**Comment by wkzsgxxn** [comment]
Hello, I am running the test with 'sh ./federatedml/test/run_test.sh', the error is as follows：
File "project/FATE/arch/api/standalone/eggroll.py", line 104, in _open_env
    return lmdb.open(path, create=True, max_dbs=1, max_readers=1024, lock=write, sync=True, map_size=10_737_418_240)
SyntaxError: invalid syntax

When I changed the code at FATE/arch/api/standalone/eggroll.py", line 104 to ‘    return lmdb.open(path, create=True, max_dbs=1, max_readers=1024, lock=write, sync=True, map_size=(10_737_418_240))’，The error has become ‘ File "/project/FATE/arch/api/standalone/eggroll.py", line 104, in _open_env
    return lmdb.open(path, create=True, max_dbs=1, max_readers=1024, lock=write, sync=True, map_size=(10,737,418,240))
TypeError: unorderable types: tuple() >= int()’

So I would like to ask you what is the reason, thank you!

**Comment by mgqa34** [comment]
> Hello, I am running the test with 'sh ./federatedml/test/run_test.sh', the error is as follows：
> File "project/FATE/arch/api/standalone/eggroll.py", line 104, in _open_env
> return lmdb.open(path, create=True, max_dbs=1, max_readers=1024, lock=write, sync=True, map_size=10_737_418_240)
> SyntaxError: invalid syntax
> 
> When I changed the code at FATE/arch/api/standalone/eggroll.py", line 104 to ‘ return lmdb.open(path, create=True, max_dbs=1, max_readers=1024, lock=write, sync=True, map_size=(10,737,418,240))’，The error has become ‘ File "/project/FATE/arch/api/standalone/eggroll.py", line 104, in _open_env
> return lmdb.open(path, create=True, max_dbs=1, max_readers=1024, lock=write, sync=True, map_size=(10,737,418,240))
> TypeError: unorderable types: tuple() >= int()’
> 
> So I would like to ask you what is the reason, thank you!

@wkzsgxxn Can you tell me the python version?  It seems that python env is a litter old, which does not support  "map_size=10_737_418_240". To support this syntax it should be update to python 3.6 or higher.

**Comment by wwwwww1020** [comment]
> config path is /fate/examples/hetero_logistic_regression/conf/guest_runtime_conf.json_hetero_logistic_regression_example_standalone_20190529012020
> jobid is hetero_logistic_regression_example_standalone_20190529012020
> Traceback (most recent call last):
> File "/fate/arch/api/utils/file_utils.py", line 40, in load_json_conf
> with open(json_conf_path) as f:
> FileNotFoundError: [Errno 2] No such file or directory: '/fate/arch/conf/server_conf.json'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
> File "../../workflow/hetero_lr_workflow/hetero_guest_workflow.py", line 22, in 
> from workflow.workflow import WorkFlow
> File "/fate/workflow/workflow.py", line 52, in 
> from workflow import status_tracer_decorator
> File "/fate/workflow/status_tracer_decorator.py", line 30, in 
> server_conf = file_utils.load_json_conf("arch/conf/server_conf.json")
> File "/usr/local/lib/python3.6/site-packages/cachetools/**init**.py", line 46, in wrapper
> v = func(*args, **kwargs)
> File "/fate/arch/api/utils/file_utils.py", line 43, in load_json_conf
> raise EnvironmentError("loading json file config from '{}' failed!".format(json_conf_path))
> OSError: loading json file config from '/fate/arch/conf/server_conf.json' failed!

Do you fix that? I got same problem with you.

**Comment by paulbaogang** [comment]
@wwwwww1020
Thank you very much for your feedback. This is an omission. We have submitted a PR to fix it. If it is more urgent, we can do this:
1. Delete the generated docker container and image.
2, pull the code.
3. Modify the build_standalone_docker.sh code and change "git archive -o ./docker/standalone/fate.tar $(git rev-parse HEAD) arch/api federatedml workflow examples" to "git archive -o ./docker/standalone /fate.tar $(git rev-parse HEAD) arch federatedml workflow examples".
4. Rebuild a docker.
Try again, thank you

**Comment by paulbaogang** [comment]
@wwwwww1020
Thank you very much for your feedback. This is an omission. We have submitted a PR to fix it. If it is more urgent, we can do this:
1. Delete the generated docker container and image.
2. pull the code.
3. Modify the build_standalone_docker.sh code and change "git archive -o ./docker/standalone/fate.tar $(git rev-parse HEAD) arch/api federatedml workflow examples" to "git archive -o ./docker/standalone /fate.tar $(git rev-parse HEAD) arch federatedml workflow examples".
4. Rebuild a docker.
Try again, thank you
