### ISSUE TITLE
Question about host and guest.

### ISSUE THREAD

**Issue by yaochitc** [WeBankFinTech/FATE#331]
I did't find any official definition about guest and host, could anyone give some introduction?

**Comment by tanmc123** [comment]
Guest can be also known as data consumer and host is data provider. Both of them are parties that involved in a federated learning task. Typically, in hetero scenario, guest is usually represent for the party with labels. The other party will be treated as host.

**Comment by yaochitc** [comment]
> Guest can be also known as data consumer and host is data provider. Both of them are parties that involved in a federated learning task. Typically, in hetero scenario, guest is usually represent for the party with labels. The other party will be treated as host.

Thanks for reply, got it!
