### ISSUE TITLE
How dose FATE work when datasets in different machines?

### ISSUE THREAD

**Issue by ijnmklpo** [WeBankFinTech/FATE#347]
I tried the standalone version hetero-logistic-regression sample and it worked well, but I still have a question that,  in the demo, the data from two parties are put in one machine, but how to configurate if the data in two different machine? thx~

**Comment by tanmc123** [comment]
In this case, standalone version doesn't work anymore. We suggest you try cluster version instead. In cluster version, data are supposed to located in different machines.

**Comment by ijnmklpo** [comment]
> In this case, standalone version doesn't work anymore. We suggest you try cluster version instead. In cluster version, data are supposed to located in different machines.

Ok, thank you! Maybe I should read the cluster deployment guide first. There also is another question😂, I have seen the cluster version demo before, and feel confused about that where would the data located when it is uploaded.

**Comment by zengjice** [comment]
> > In this case, standalone version doesn't work anymore. We suggest you try cluster version instead. In cluster version, data are supposed to located in different machines.
> 
> Ok, thank you! Maybe I should read the cluster deployment guide first. There also is another question😂, I have seen the cluster version demo before, and feel confused about that where would the data located when it is uploaded.

hi, when running in cluster mode, eggroll is a distributed storage computing engine, the actual storage location of the data is fragmented and stored in different storage nodes by eggroll.

**Comment by ijnmklpo** [comment]
> > > In this case, standalone version doesn't work anymore. We suggest you try cluster version instead. In cluster version, data are supposed to located in different machines.
> > 
> > 
> > Ok, thank you! Maybe I should read the cluster deployment guide first. There also is another question😂, I have seen the cluster version demo before, and feel confused about that where would the data located when it is uploaded.
> 
> hi, when running in cluster mode, eggroll is a distributed storage computing engine, the actual storage location of the data is fragmented and stored in different storage nodes by eggroll.

ok, I see. But where can I find the model result and predicted data when using cluster mode, will they be pushed to local machine which I uploaded the data?
