### ISSUE TITLE
When building a securetree model, if the user in the Party A don't have the data in the Party B, what will the model inference?

### ISSUE THREAD

**Issue by YijiaZhang1996** [WeBankFinTech/FATE#350]
Hi,I am confused about when we built a securetree model, if the user in the Party A don't have the data in the Party B, what will the model inference for him/her?
Will the model makes a auto-completion for him/her by some strategy? or just filter it and do nothing? Thanks for answering!

**Comment by mgqa34** [comment]
Now Fate's secureboost does not support missing value now. It will support it in later version.

**Comment by mgqa34** [comment]
long time no reply, close this issue
