### ISSUE TITLE
Regarding the introduction of affine cipher as an HE option

### ISSUE THREAD

**Issue by lyyanjiu1jia1** [WeBankFinTech/FATE#353]
Current project provides the famous Paillier cryptosystem as a homomorphic encryption tool for secure information computation and exchange. Indeed it is secure and effective. However, we question its efficiency and necessity. As a public-key cryptosystem, Paillier is computationally complex, and perfectly fits the situation in which multiple parties encrypt messages while one party holding the privacy key can decrypt them. This situation is definitely not what is like in SecureBoosting. We recommend using symmetric encryption methods, e.g., affine cipher, to accelerate the homomorphic computation process. Careful key selection would be needed to ensure the security.

**Comment by dylan-fan** [comment]
thank for your contribution, we will evaluation your codes
