### ISSUE TITLE
Deployment error happened after installing MySQL

### ISSUE THREAD

**Issue by TerrenceKao** [WeBankFinTech/FATE#364]
I am trying to deploying the cluster-verion FATE and exactly followed the instructions. However I stacked and got the error "ERROR 2002 (HY000): Can't connect to local MySQL server through socket" after excuting ``$/data/projects/common/mysql/mysql-8.0/bin/mysql` -uroot -p -S /data/projects/common/mysql/mysql-8.0/mysql.sock``.  Also I noticed MySQL service was not started. As a temptation to solve this issue, I installed mariadb-server, started MySQL service but still got the same error. Can anyone let me know why this happened and how to solve it?

**Comment by forgivedengkai** [comment]
1.Check  whether  mysql is started  。
2.if   mysql is started,check whether the file /data/projects/common/mysql/mysql-8.0/mysql.sock  exists .if not exists,  try to  check mysql's configration  to find out where is the mysql.sock
