### ISSUE TITLE
when i run logistic_regression,i come to "fail to post status running" problem

### ISSUE THREAD

**Issue by noeye** [WeBankFinTech/FATE#385]
config path is /opt/FATE/examples/hetero_logistic_regression/conf/arbiter_runtime_conf.json_hetero_logistic_regression_example_standalone_20190806234846
jobid is hetero_logistic_regression_example_standalone_20190806234846
fail to post status running
Finish encrypt parameter check!
Finish evaluation parameter check!
Finish predict parameter check!
Finish predict parameter check!
Finish evaluation parameter check!
Finish workerflow parameter check!
Finish init parameter check!
Finish encode parameter check!
Finish encode parameter check!
Finish intersect parameter check!
Finish init parameter check!
Finish encrypt parameter check!
Finish logistic parameter check!
Finish encrypt parameter check!
Finish scale parameter check!
Finish one_vs_rest parameter check!
Finish all parameter checkers
Get in base workflow initialize
Finish init parameter check!
Finish encrypt parameter check!
Finish logistic parameter check!
Finish predict parameter check!
Finish evaluation parameter check!
Finish workerflow parameter check!

**Comment by zazd** [comment]
if the PYTHONPATH been set ?

**Comment by mgqa34** [comment]
long time no reply, close this issue
