### ISSUE TITLE
Cluster deployment problem

### ISSUE THREAD

**Issue by ijnmklpo** [WeBankFinTech/FATE#390]
Hello, I meet a problem when I deploy the cluster version FATE in a linux server, the OS of the server is centos6.5. 
It failed in the step of running "bash auto-deploy.sh".  
<img width="800" alt="image-20190808094139603" src="https://user-images.githubusercontent.com/9210893/62669614-c61b9080-b9c2-11e9-9ac4-dc8a79395fde.png">
The result is shown like above. When I typed the password of user "app" which I masked in screenshot, it was blocked for a while and then disconnected from the server. 
BTW, I edited "configurations.sh" file following the issue https://github.com/WeBankFinTech/FATE/issues/278. And just modify the ip, I wonder if there is problem with my process, Thank you.

**Comment by paulbaogang** [comment]
The operating system requires centos7.2, and it is recommended to use 7.2.
In addition, the app user needs to be free from sudo to root and needs to be configured.
please try,thanks.

**Comment by ijnmklpo** [comment]
> The operating system requires centos7.2, and it is recommended to use 7.2.
> In addition, the app user needs to be free from sudo to root and needs to be configured.
> please try,thanks.

Ok, I will try the deployment on Centos7.2.
I have given the app user root right, and you mentioned "the app user needs to be configured", I am not sure which step you mean, would you mind be more specific, thank you so much!
