### ISSUE TITLE
Cluster deployment question : about configuration.sh

### ISSUE THREAD

**Issue by three3stones** [WeBankFinTech/FATE#391]
Hello!
When I carry out the step 4 "Project Deployment", I have a question with the setting of the file configuration.sh.
My situation: three virtual machines，their ips: ***16, ***17, ***18 (Replaced with 16 17 18)
                     And 16 is host ; 17 is guest ; 18 is arbiter.
　　　　　   And each machine contains all the modules.

The following is my specific settings in one machine.
#!/bin/bash
user=app
dir=/data/projects/fate
mysqldir=/data/projects/common/mysql/mysql-8.0
javadir=/data/projects/common/jdk/jdk1.8
venvdir=/data/projects/fate/venv
redisip=(16 17 18)
redispass=fate1234
partylist=(9999 10000 10001)
JDBC0=(16 fate0 fate Fate123#$)
JDBC1=(17 fate1 fate Fate123#$)
JDBC2=(18 fate2 fate Fate123#$)
iplist=(16 17)
fedlist0=(16)
fedlist1=(17)
fedlist2=(18)
meta0=(16)
meta1=(17)
meta2=(18)
proxy0=(16)
proxy1=(17)
proxy2=(18)
roll0=(16)
roll1=(17)
roll2=(18)
egglist0=(16)
egglist1=(17)
egglist2=(18)
tmlist0=(16)
tmlist1=(17)
tmlist2=(18)
serving0=(16)
serving1=(17)
serving2=(18)
exchangeip=18

Is there a mistake in my configuration?
Is the configuration of the three machines the same?
Thank you for your answer！

**Comment by paulbaogang** [comment]
At present, the deployment supports single-party deployment and simultaneous deployment of two-party parties. Currently, the simultaneous deployment of the three parties is not supported. You can deploy both parties first, and then add one party.

**Comment by three3stones** [comment]
Thank you for your reply！
I will try to deploy both parties simultaneously, and is the configuration of the two machines the same?
Do they have the same file "configuration.sh"?

**Comment by three3stones** [comment]
These are the modified settings. Is it correct?

#!/bin/bash
user=app
dir=/data/projects/fate
mysqldir=/data/projects/common/mysql/mysql-8.0
javadir=/data/projects/common/jdk/jdk1.8
venvdir=/data/projects/fate/venv
redisip=(16 17)
redispass=fate1234
partylist=(9999 10000)
JDBC0=(16 fate0 fate Fate123#$)
JDBC1=(17 fate1 fate Fate123#$)
iplist=(16 17)
fedlist0=(16)
fedlist1=(17)
meta0=(16)
meta1=(17)
proxy0=(16)
proxy1=(17)
roll0=(16)
roll1=(17)
egglist0=(16)
egglist1=(17)
tmlist0=(16)
tmlist1=(17)
serving0=(16)
serving1=(17)
exchangeip=
