### ISSUE TITLE
the prediction can only predict part of the input data table

### ISSUE THREAD

**Issue by staryorange** [WeBankFinTech/FATE#392]
Hello, when I run the "predict" mode in the cluster form, initially, the prediction work well for about 20000 samples when the num_trees = 2, while when the model is trained by the num_trees = 10, the prediction can only predict part of the input data table. 

And I found the problem can be associated with the processor launched by the "egg" module. However, there is no place that I can find the exception information in the egg nor in the processor logs file. And the port range from 50001 to 50008 which are all active after checking.

I am confused about the stability of the trained model, can anyone give me some suggestions?

**Comment by mgqa34** [comment]
Can you check logs in roll ? Maybe help with error\console.log under roll's log directory
