### ISSUE TITLE
A question about confused parameter in the  Secure Tree Model

### ISSUE THREAD

**Issue by YijiaZhang1996** [WeBankFinTech/FATE#393]
There is a confused parameter in the  Secure Tree Model: 

criterion_params

Could anyone help to explain what does this parameter work for

And I can't find "gamma" parameter which alias is min_split_loss. The explaination of this parameter in the online XGBoost document is minimum loss reduction required to make a further partition on a leaf node of the tree. The larger gamma is, the more conservative the algorithm will be.

**Comment by mgqa34** [comment]
1. criterion_params in FATE is a list, now only support xgboost-like split_evaluator，and the only element in it is a float number, the parameter reg_lambda\lambda( L2 regularization term on weights) in xgboost. 
2. gamma(min_split_loss) in Xgboost  is min-loss-reduction to judge split or not, min_impurity_split works the same in FATE

**Comment by mgqa34** [comment]
long time no reply,  close
