### ISSUE TITLE
need predict script method support and api to read predict result

### ISSUE THREAD

**Issue by minfree123** [WeBankFinTech/FATE#5]
the current examples support run in train and cross_validation method,missing predict method support.
also i think there is no api to read out the saved pridict result.
it would be very grateful,these features are added.

**Comment by dylan-fan** [comment]
thanks for your advice， we will add these features in next release version

**Comment by tanmc123** [comment]
In this version, predict functions is provided in examples, and the result will be available in logs. The script to show predict result has not finished yet. It will be an enhancement in next version.
