### ISSUE TITLE
Add documentation for API

### ISSUE THREAD

**Issue by yankang18** [WeBankFinTech/FATE#51]
For now, it is a lack of documentation for public APIs (e.g., eggroll APIs and operators such as HeterologisticGradient.fore_gradient()), which makes the whole framework hard to use. 

It would be much better to add clear documentation and even some examples for these APIs.

**Comment by dylan-fan** [comment]
It's a good idea. In fact, we're already doing it. We will use the Sphinx tool to do automatic API document generation from source code file

**Comment by yankang18** [comment]
+1

**Comment by tanmc123** [comment]
@yankang18 To add such documents, please use the same format of annotation while coding. We will make a documentation after that.
