### ISSUE TITLE
One-second latency after each transfer event

### ISSUE THREAD

**Issue by qjing666** [WeBankFinTech/FATE#55]
Note that the Proxy.Packet (in arch/networking/proxy/src/main/java/com/webank/ai/fate/networking/proxy/grpc/client/DataTransferPipedClient.java line 96)do one extra read from the pipe which is already drained, and the read function set a timeout of 1 second to ensure the pipe has no packets. This may cause an one-second latency at the end of each transfer event. 

This can be solved by adding a "isDrain" check before polling packets from the pipe. 

I have tried to add a line of code "if (isDrained()) return result;" between line 66 and line 67 of PacketQueuePipe.java(in arch/networking/proxy/src/main/java/com/webank/ai/fate/networking/proxy/infra/impl/) , the training examples works properly and the latency is removed.

**Comment by maxwong** [comment]
Thanks for your feedback. We are looking into it.

**Comment by dylan-fan** [comment]
thanks，welcome to FATE contributor

**Comment by dylan-fan** [comment]
merge
