### ISSUE TITLE
Docker support

### ISSUE THREAD

**Issue by ljch2018** [WeBankFinTech/FATE#6]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by maxwong** [comment]
Hi ljch2018, please provide more details of your request. Your request seems like a request template.

Docker is supported in standalone deployment btw.  You may want to have a look at `FATE/docker/standalone/`. Thanks.

**Comment by lijiacaigit** [comment]
HI !  please provide a cluster-deploy for docker by docker-compose，so we can use it straight!,Parameters preferably support one-click configuration. your packaging.sh exits error "targets=`find "$base_dir" -type d -name "target" -mindepth 2`"

**Comment by maxwong** [comment]
Hi lijiacaigit, thanks for your advice. Docker images for cluster deploy has been planned and will be available in one of future releases, and we are working on it. For now I'm afraid that you have to deploy manually.

As for the error you reported, packaging.sh has been tested in our env before releasing. So could you provide us the followings:
a. The error message, either copying it or uploading a screenshot;
b. Your environment info, e.g. operating system and its version, bash version etc.

Thanks.

**Comment by lijiacaigit** [comment]
Hi.
1.when will the docker version of cluster deployment be available? 
2.packaging.sh has `find "$base_dir" -type dir -name "target" -mindepth 2`",you can execute the command in your terminal , and you will get error like "find: Arguments to -type should contain only one letter"

**Comment by maxwong** [comment]
> Hi.
> 1.when will the docker version of cluster deployment be available?
> 2.packaging.sh has `find "$base_dir" -type dir -name "target" -mindepth 2`",you can execute the command in your terminal , and you will get error like "find: Arguments to -type should contain only one letter"

1. We are planning to contain cluster deployment on docker at version 0.3. Hopefully in late April or early May this year.
2. Checked manual and `-type d` works better indeed. Will change this soon. 

Thank you for the feedback.

**Comment by lijiacaigit** [comment]
Ok！
Mysql service required for cluster deployment?
When I deployed, I found that some environment dependencies were ambiguous，your documentation is more detailed, and it will be easier to deploy, preferably with one-click configuration

**Comment by maxwong** [comment]
> Ok！
> Mysql service required for cluster deployment?
> When I deployed, I found that some environment dependencies were ambiguous，your documentation is more detailed, and it will be easier to deploy, preferably with one-click configuration

Yes, mysql service is required for cluster deployment.
Thank you for your advice and we will add dependency description in documents. 
And we will try to automate deployment, though it could be quite a process.

**Comment by maxwong** [comment]
Closing this issue as issues has been resolved. User may reopen it if there is further question on this issue.
