### ISSUE TITLE
Numeric Stable for sigmoid & log_logistic

### ISSUE THREAD

**Issue by dylan-fan** [WeBankFinTech/FATE#65]
1. 
sigmoid(x) 
if x >0 , sigmoid(x) = 1/（1+exp(-x)）
if x <=0, sigmoid(x) = exp(x)/（1+exp(x)）

2. log_logistic
if x >0 , log_logistic(x) = -log *（1+exp(-x)）
if x <=0, log_logistic(x) = x - log *（1+exp(x)）

**Comment by tanmc123** [comment]
Merged into develop branch

**Comment by tanmc123** [comment]
When x is larger than 710, exp(x) will overflow:
>> np.exp(710)
inf

Thus, for numeric stability, made a change by the formula above.
