### ISSUE TITLE
accurate average gradient and loss

### ISSUE THREAD

**Issue by drougon** [WeBankFinTech/FATE#93]
**Is your feature request related to a problem? Please describe.**
current average algorithm is E = (s1/cnt1 + s2/cnt2 + ...)/partitions， not a really  mean

**Describe the solution you'd like**
E = (s1 + s2 + ...)/(cn1 + cnt2 + ...)

**Comment by dylan-fan** [comment]
In fact, we evaluator two methods in some datasets. The results show that the two methods are very close. 
But your solution seems to be better mathematically, so we merged your pr.
